# Site settings
title: Uvindu Bro Blog
description: A blog about Uvindu Bro Blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: UvinduBro
user_description: 
user_title: Bot Developer
email: gmp@telegmail.com
twitter_username: 
github_username:  UvinduBroOrg
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
